title: Aditya Gupta
logo: /assets/img/adi_photo.jpg
description: Email: reachme.adityag@gmail.com (mailto:reachme.adityag@gmail.com) \n Phone: +91-9844477649
show_downloads: false
theme: jekyll-theme-minimal
